<?php
return array(
	'welcome_message' => 'Welcome again',
	'vote_added' => 'Thank you for voting!',
	'liczbaglos' => 'Number of votes: ',
	'vote_own_file' => 'You cannot rate your own materials!',
	'zaloguj_sie' => 'Log in',
	'edit_profile_plec' => 'Specify your sex',
	'user_plec' => 'Sex',
	'user_male' => 'Male',
	'user_female' => 'Female',
	'see_more' => 'See more',
	'follow_by_count' => 'Observed by:',
	'fast_normal_view' => 'standard view',
		
	'js_cookie_policy_info' => '<b>Note: this website takes advantage of cookie files</b>We use the information gathered thanks to cookies and similar technologies for advertisement and statistical purposes, as well as to adjust the services provided by the website to the needs of the users. The aforementioned files may be also utilized by cooperating advertisers and surveying companies. <br/> If you accept the utilization of cookies, they will be saved in your browser’s memory. By checking the settings of your browser, you may also change the options concerning storage of cookies. More info: <a style="color: black; font-weight: bold;" href="/post/regulamin.html">Terms and Conditions</a>',
	'js_cookie_policy_info_close' => 'Close',
		
		
	'js_datepicker_short_months' => 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
	'js_datepicker_months' => 'January|February|March|April|May|June|July|August|September|October|November|December',
	'js_datepicker_week' => 'Week',
	'js_datepicker_day_names' => 'Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday',
	'js_datepicker_day_names_short' => 'Sun|Mon|Tue|Wed|Thu|Fri|Sat',
	'js_datepicker_day_names_minshort' => 'Su|M|Tu|W|Th|F|Sa',
	'js_datepicker_today' => 'Today',
	'js_datepicker_next' => 'Next&#x3e;',
	'js_datepicker_prev' => '&#x3c;Previous',
	'js_datepicker_close' => 'Close',
		
	'js_alert' => 'Attention!',

	'js_app_delete' => 'delete',
	'js_app_file' => 'Material',
	'js_app_none_viewed' => 'Your friend has not browsed any materials yet',
	'js_app_request' => 'Invitation to the Share app',
	'js_app_add_freind' => 'Add friend',
	'js_app_saved_sction' => 'Action has been saved!',
	'js_form_validate_all' => 'All blanks must be filled in',
	'js_report_duplicate_msg' => 'If you want, you may provide additional pieces of information, such as: link to the material, duplicate, etc.',
	

	
	'js_up_error_url' => 'Improper image link!',
	'js_up_error_exists' => 'The image has yet been posted!',
	'js_up_error_url' => 'Provide proper image link!',
	'js_up_add_images' => 'Add photos',
	'js_up_longer_caption' => 'Provide a longer description to be added ( min. %s characters)',
	'js_up_select_files' => 'Upload files from your hard drive',
	'js_up_exceed_limit' => 'You cannot add more files',
		

	'js_load' => 'Loading...',
	'js_com_adding' => 'Adding your comment... <img src="/images/loading.gif" />',
	'js_com_empty' => 'Provide the content of the comment',
	'js_delete_comment' => 'Deleting your comment... <img src="/images/loading.gif" />',
	'js_alert_jquery' => 'Unidentified jQuery error has occured',
	'js_pw_sending' => 'Sending PM <img src="/images/loading.gif" />',
		
	'js_com_answer_emots' => 'While answering, you can also use emoticons and BBCode, for example:  :), :-( ,[quote][/quote], [u][/u] itp.',
	'js_com_answer_add' => 'Add',
	'js_com_answer_reject' => 'Cancel',
		
	'js_com_hidden_show' => 'show',
	'js_com_hidden_hide' => 'hide',
		
		
	'js_popup_wait' => 'or wait',
	'js_popup_seconds' => 'second(s)',
	'js_popup_close' => 'Close',
		
		
	'js_bbcode_video_enter_url' => 'Provide Youtube link',
	'js_bbcode_video_enter' => 'Type here',
	'js_bbcode_video' => 'Provide proper Youtube link',
	'js_bbcode_bold' => 'Bold',
	'js_bbcode_italic' => 'Incline',
	'js_bbcode_underline' => 'Underline',
	'js_bbcode_center' => 'Center text',
	'js_bbcode_quote' => 'Quote',
	'js_bbcode_video_url' => 'Link to Video',
	'js_6d' => 'Happy face',
	'js_bbcode_sad' => 'Sad face',
	'js_bbcode_kiss' => 'Send a kiss',
	'js_bbcode_tongue' => 'Poke tongue',
	'js_bbcode_threatens' => 'Threaten',
	'js_bbcode_lol' => 'Amazing LOL',
	'js_bbcode_eyelet' => 'Wink',
	'js_bbcode_happy' => 'Grin',
	'js_add_file_animation' => 'Add a file',
	'js_add_file_animation_stop' => 'Stop',
	'js_add_file_animation_error' => 'Error',
	'js_report_title' => 'Report',
	'js_report_sending' => 'Sending report... <img src="/images/loading.gif" />',
	'js_report_ok' => 'Report has been sent!',
		
		
		
	'widget_social_nk' => 'Share on Nasza-Klasa.',
	'widget_social_fb' => 'Share on Facebook.',
	'widget_social_gg' => 'Change your Gadu-Gadu status! (up to ver. 8.0)',
	'widget_social_forum' => 'Take part in discussion!',
	'widget_social_jm' => 'Share on Joe Monster!',
	'widget_social_wykop' => 'Share on Wykop!',
		
	'added_by' => 'by',
	'autopost_blocked' => 'The material has been rated as 18+. To see it, log in to your Facebook account.',
	'page_empty' => 'No website has been found',
	'page_private' => 'Only registered users may access this section of the website',
	'page_read_more' => 'Read more',
	'article_show_all' => 'SHOW ALL ▼',
		
	'date_time_months' => 'January|February|March|April|May|June|July|August|September|October|November|December',
	'date_time_minutes' => ' a moment ago',
	'date_time_minutes_1' => ' a minute ago',
	'date_time_minutes_2' => ' minutes ago',
	'date_time_minutes_3' => ' minutes ago',
	'glosuj' => 'Vote',
	'next' => 'Next',
	'prev' => 'Previous',
	'strona' => 'Enter the site number:',
	'null' => 'No site found.',
	'zobaczinne' => 'Check the user’s profile and other materials',
	'powtorka' => 'Replay',
	'nafejsa' => 'Share on Facebook',
	'noscript' => 'Your browser does not support JavaScript. To take advantage of all the services provided by the website, install a different browser, such as: Mozilla, Opera...',
	'user_reset_password_title' => 'Remind my password',
	'user_account_active' => 'Your account has been activated',
	'user_reset_password_email' => 'Greetings!<br />You have sent a request to have your password reminded.<br />Here is your password:',
	'user_resend_activation_email' => 'Greetings!<br />You have sent a request to resend the activation link.<br />Here is the new link: ',
	'user_resend_activation_title' => 'Activation link.',
	'find_smilar' => 'Look for similar',
	'button_smilar' => 'Similar',
	'err_nieznane_roz' => 'File not supported',
	'nierozstrz' => 'Unsolved',
	'login_top1' => 'Log in to the website',
	'login_top2' => 'Log in',
	'login_top3' => 'Register to take advantage of all the services provided by the website',
	'login_top4' => 'register',
	'login_top5' => 'Your profile',
	'nothing_to_display' => '<h3 style="padding: 10px;">No items to be shown</h3>',
	'users_online_empty' => '<h3 style="padding: 10px;">No user logged in</h3>',
	'login_top6' => 'Edit profile',
	'login_top7' => 'Administration panel',
	'login_top8' => 'Administration Panel',
	'login_top9' => 'Moderation Panel',
	'login_top10' => 'Private Messages Panel',
	'login_top11' => 'Private Messages',
	'login_top12' => 'Log out',
	'login_top13' => 'My materials',
	'login_top14' => 'close',
	'login_top15' => 'Notifications',
	'search_phrase' => 'Search',
	'search_type_image' => 'Image',
	'search_type_video' => 'Video',
	'search_type_text' => 'Text',
	'search_type_article' => 'Article',
	'search_type_gallery' => 'Gallery',
	'search_where' => 'Where:',
	'search_on_main' => 'Main page',
	'search_on_wait' => 'Added',
	'search_on_all' => 'All',
	'search_sorting' => 'Sort:',
	'search_sorting_accuracy' => 'Accuracy',
	'search_date_asc' => 'Dates [increasing]',
	'search_date_desc' => 'Dates [decreasing]',
	'search_vote_asc' => 'Votes [increasing]',
	'search_vote_desc' => 'Votes [decreasing]',
	'search_view' => 'View:',
	'search_view_normal' => 'Big icons',
	'search_view_thumbs' => 'Miniatures',
	'search_type_ranking' => 'Ranking',
		
	'load_more_files' => 'Next page',
	'widget_to_top' => 'To the top',
	'contest_not_created' => 'No events available.',
	'konkurs' => 'Check',
	'contest_1' => 'Please wait',
	'contest_2' => 'You cannot vote in the same event twice',
	'contest_3' => 'The event has ended.',
	'contest_4' => 'Your vote has been submitted',
	'contest_5' => 'You have voted for this post.',
	'contest_6' => 'Provide a title of your post to add it to the event',
	'contest_7' => 'Previous post',
	'contest_8' => 'Next post',
	'contest_9' => 'Add your description to the image:',
	'contest_10' => 'Title:',
	'contest_11' => 'Description:',
	'contest_12' => 'The event ends:',
	'contest_13' => 'Time remaining:',
	'contest_14' => 'Your post has been added',
	'contest_15' => 'No voices left',
	'contest_16' => 'The event has ended',
	'contest_17' => 'User',
	'contest_18' => 'Time remaining: ',
	'contest_19' => 'No participants',
	'contest_20' => 'poor ↓',
	'contest_21' => 'great ↑',
	'contest_22' => 'Votes left:',
	'contest_23' => 'Invalid event or the event has ended',
	'contest_24' => 'The even has been won by: <b> %s </b>',
	'contest_25' => 'Unsolved.',
	'contest_26' => 'Ended: ',
	'contest_27' => '%s posts submitted for the event.',
	'contest_28' => '%s materials submitted for the event.',
	'contest_29' => 'Title of the material',
	'contest_30' => 'Votes: ',
	'contest_31' => 'Add a description',
	'contest_32' => 'No event-related posts',
	'contest_33' => 'Do not add new descriptions so frequently. Consider if they are good enough to be submitted',
	'contest_34' => 'You cannot add more than one description',
	'contest_35' => 'You have already voted for this description',
	'contest_36' => 'You must log in to vote',
	'contest_opinion' => 'Rating',
	'contest_comments' => 'Comments',
	'contest_share' => 'Shares',
		
	'user_profile_add_about_me' => 'No description',
	'user_actions_register' => 'You haven’t got an account?',
	'user_actions_recover' => 'Forgot your password?',
	'user_actions_activation_link' => 'Activation link has not yet been sent?',
	'all_7' => 'Register',
	'user_actions_recover' => 'Recover your password',
	'all_9' => 'Send again',
	'user_log_in' => 'Log in',
	'user_connect_description' => 'Take advantage of automatic logging to our website.',
	'all_12' => 'Thanks to integration of your account with our website, you will be logged in during every single visit.',
	'common_login' => 'Log in',
	'connect_facebook' => 'Log in with Facebook',
	'connect_nk' => 'Log in with NK',
	'user_actions_back_login' => 'Return to the Log in page',
	'user_set_email' => 'Enter your e-mail',
	'all_18' => 'The account has already been created ?',
	'all_reset_password' => 'Password reminder',
	'all_resend_activation' => 'Activation link',
	'lang_changed' => 'Language has been changed',
	'lang_default' => 'Default language has been set',
	'lang_none' => 'No ISO code available for this language',
	'widget_wait_box' => 'Recently popular',
	'najlepsze' => 'Rated highly',
	'plus' => 'Plus',
	'minus' => 'Minus',
		//'vipv' => 'Vip',
	'mod_main' => 'main page',
	'mod_wait' => 'added',
	'mod_archive' => 'archival materials',
	'mod_delete' => 'delete',
	'anonymous_login' => 'Anonymous',
	'add_ranking_next' => 'Add a new item to the ranking',
		
	'top_image' => 'pictures and photos',
	'comments_add_facebook' => 'Comment on Facebook',
	'top_lub' => 'or',
	'top_all' => 'all',
	'top_image' => 'pictures and photos',
	'top_video' => 'video',
	'top_text' => 'text',
	'top_article' => 'articles',
	'top_gallery' => 'galleries',
	'top_ranking' => 'ranking',
		

	'top_popular_menu' => 'Popular',
	'top_popular' => 'Popular posts',
	'top_pinit_top_menu' => 'Top',
	'top_pinit_top' => 'Top rated posts',

	'widget_filter' => 'Show:',
	'top_admin' => 'Contact website Administration',
	'menu_top' => 'Top 10',
	'menu_up' => 'Add a new material to the website',
	'top_rand' => 'Random material',
	'menu_wait' => 'Added materials – you can vote for recently submitted materials here',
	'menu_main' => 'Main page',
	'top_rule' => 'Terms and Conditions',
	'top_arch' => 'Archival materials',
	'menu_rss_main' => 'Main page Rss',
	'menu_rss_waiting' => 'Added Rss',
	'js_jquery_processing' => 'Wait a moment, please. The requested data is being processed',
	'menu_shared' => 'Check the top share FB materials',
	'menu_nk' => 'Check the top share Nasza Klasa materials',
	'menu_nk_menu' => 'Top<b style="color:green;"> NK</b>',
	'menu_google' => 'Check top Google Plus shares (the list is updated every 15 minutes)',
	'menu_generator' => 'Memes',
	'menu_google_menu' => 'Top<b style="color:red;"> Google</b>',
	'menu_top_menu' => 'Top',
	'menu_generator_menu' => 'Memes',
	'menu_up_menu' => 'Add',
	'menu_random_menu' => 'Random',
	'menu_main_menu' => 'Main page',
	'menu_contest_menu' => 'Events',
	'top_fb_menu' => 'Top<b style="color:#0069d2;"> Facebook</b>',
	'menu_waiting_menu' => 'Added',
	'topdemot_all' => 'All',
	'topdemot_tydz' => 'Last week',
	'topdemot_mies' => 'Last month',
	'topdemot_24' => 'Last 24h',
	'topdemot_rok' => 'Last year',
	'topdemot_1' => 'Rating',
	'topdemot_2' => 'Votes',
	'topdemot_3' => 'Comments',
	'topdemot_4' => 'Users',
	'bottom_rule' => 'Regulations',
	'bottom_contact' => 'Contact us',
	'bottom_stats' => 'Currently we have  %s %s online. %s registered users and %s guests.<br /> Joined today: %s, Yesterday: %s, All: %s <br />',
	'bottom_stats_one_user' => 'user',
	'bottom_stats_many_users' => 'users',
	'dodany' => 'Added',
	'favourites_short' => '+fav.',
	'blok_glos' => 'Log in to vote and add materials to favorites',
	'add_for_logged_in' => 'Log in to add materials',

		
	'favourites_added' => 'Added to favorites',
	'favourites_already_added' => 'The material has already been added to favorites.',
	'favourites_deleted' => 'Deleted from favorites',
	'favourites_login' => 'Log in',
	'favourites_delete' => 'Delete from favorites',
	'favourites_add' => 'Add to favorites',
	'ulub_link' => 'Add',
	'ulub_del' => 'Deleted from favorites',
		
		
	'follow_added' => 'Added to followed',
	'follow_already_following' => 'You are following this user',
	'follow_delete' => 'Delete',
	'follow_deleted' => 'Deleted from followed',
	'follow_new_files' => 'The followed users have added new materials.',
	'wyszukaj' => 'Find something interesting...',
	'report_this' => 'report',
	'regulamin' => 'You must accept the Terms and Conditions',
	'upload_source' => 'Source: ',
	'user_only_logged' => 'This function is only available for logged users',
	'add_is_private' => 'Private ?',
	'usuniety' => 'Material has been deleted',
		
	'accept_rules' => 'Material has been moved to the main page!',
	'migracja' => 'Material has been successfully moved',
	'archive_voted' => 'Thank you for voting. The material may be published in the Added section :)',
	'item_not_exists' => 'No file with that ID',
		
	'video_big' => 'Change resolution',
	'przeniesiony' => 'Material has been moved to the Added section',
		
	'cenzura' => '*****',
	'edit_profile_avatar' => 'Change your Avatar',
	'edit_profile_changed' => 'Your data has been updated',
	'edit_profile_omnie' => 'About me:',
	'edit_profile_tolong' => 'The description is too long',
	'edit_profile' => 'Profile editing:',
	'edit_profile_birth_date' => 'Provide your date of birth',
	'edit_profile_extensions' => 'Acceptable file formats: gif, jpg, png',
	'edit_profile_email' => 'E-mail:',
	'edit_profile_password' => 'New password:',
	'edit_profile_save' => 'Save the changes',
		
	'widget_best_files_title_block' => 'Recommended materials',
		
	'widget_gag_recomended_posts' => 'Recommended',
		
	'widget_gag_popular_posts' => 'Popular materials',
	'widget_gag_popular_posts_next' => 'Next »',
	'widget_gag_popular_posts_prev' => '« Prev',
		
	'widget_friends_1' => 'Friends ',
	'widget_friends_2' => 'Add more friends',
	'widget_friends_3' => 'Loading...',
	'widget_friends_4' => 'Launch the app to see the recent actions of your friends.',
	'widget_friends_5' => 'Your account',
	'widget_friends_6' => 'Recent actions',
	'widget_friends_7' => 'On',
	'widget_friends_8' => 'Recently published:',
	'widget_friends_9' => 'Check <strong>what your friends watch</strong> and share your materials with them. All you need to do is to click the"<strong><a href="/connect/facebook/">Log in icon </a></strong>"!',
	'widget_float_1' => 'You can also navigate using arrows',
	'widget_float_2' => 'Slideshow',
	'widget_float_3' => 'Followed',
	'widget_float_4' => 'Added v2',
	'widget_float_5' => 'Logged users',
	'widget_history_view' => 'Viewed %1$s %2$s',
	'widget_history_login' => 'Logged in %2$s',  
	'widget_history_comment' => 'Added comments %1$s %2$s',  
	'widget_history_add' => 'Added materials(%3$s) %1$s %2$s',  
	'widget_history_vote' => 'Voted (%3$s) for %1$s %2$s',
	'widget_history_connect' => 'Registered via the application %3$s %2$s',
	'widget_history_register' => 'Registered on the website %2$s',  
	'widget_history_favorites-add' => 'Added %s to favorites  %2$s',  
	'widget_history_favorites-delete' => 'Deleted %1$s from favorites %2$s',	
	'widget_history_none' => 'The user has not performer any action recently',
	'widget_only_adult_title_block' => 'Warning ! ! !',
	'widget_only_adult_content' => 'The website is for 18+ only. If you are a mature individual, click the button below.',
	'widget_only_adult_close' => 'I am 18 +',
	'widget_only_adult_dismiss' => 'Leave.',
		
	'fast_nav' => 'Toggle materials by pressing <b>left/right arrow</b> or <b>z/x buttons</b>.',
	'user_ban_info' => 'Your account has been banned. You cannot perform this action.',
	'ban_user' => 'User has been banned',
	'user_permissions' => 'No authorization to perform this action.',
	'ban_ile' => 'User banned till:',
	'laduje_user' => 'Loading. Please wait',
	'widget_url_copy_action' => 'Copy the link and paste it on a forum, blog, or anywhere you want.',
	'na_minus' => 'Rate as Poor ',
	'na_plus' => 'Rate as Great',
	'niedozwolone' => 'Improper symbols or characters have been used while filling in the form ( accepted symbols: A-Z, 0-9, _#()\-=+"" )',


		
	'modified' => 'Modified by ',
	'user_mod_shares' => 'Share',
	'user_mod_comment_moderate' => 'Moderate',
	'user_mod_item_view' => 'See the material',
	'user_report_item' => 'Report',
	'mod_del' => 'Delete',
	'mod_com' => 'Comments',
	'user_mod_date' => 'By date',
	'user_mod_opinion' => 'By rating',
	'user_mod_votes' => 'By number of votes',
	'mod_comm' => 'By number of comments',
		//'mod_vipm' => 'Vip Materials',
	'user_error_email' => 'There is no user registered for this e-mail address',
	'user_reset_password_sent' => 'The reminder has been sent to the provided e-mail address',
	'user_resend_activation_sent' => 'New activation link has been sent to the provided e-mail address',
	'nie_wyslane' => 'Reminder has not been sent',
	'user_tp1' => 'Added materials',
	'user_tp2' => 'from which',
	'user_tp3' => 'on the main page and',
	'user_tp4' => 'in the added section',
	'user_tp5' => 'points for submitted files and',
	'user_tp6' => 'points for posted comments',
	'user_msg' => 'Send a message to the user',
	'user_add' => 'Added materials:',
	'user_av' => 'User’s Avatar',
	'user_ban' => 'Ban the account',
	'user_ban_week' => 'For a week',
	'user_ban_month' => 'For a month',
	'user_ban_alltime' => 'Forever',
	'user_history' => 'History',




	'comments_add_list' => 'Comment',

	'pw_new_message' => 'New PM from',
	'pw_new_message_sended' => 'sent',
		
	'pw_blad_err' => 'An unknown error has occurred. Please, contact with the administration of the website.',
	'login_brak_user' => 'User has not been found in the database',
	'pw_error_own_account' => 'You cannot send a PM to yourself',
	'pw_error_ban' => 'Your account has been banned. You cannot send any PMs.',
	'pw_error_flood' => 'You can sent only one PM per 2 minutes',
	'pw_message_sent' => 'Private Message has been sent',
	'pw_error_delete' => 'Error. The message has not been sent!',
	'pw_user_from' => 'From',
	'pw_message_subject' => 'Topic',
	'pw_data' => 'Date',
	'pw_message_delete' => 'Delete',
	'pw_messages_empty' => 'No message',
	'pw_user_to' => 'To',
	'pw_status' => 'Status',
	'pw_status_deleted_before_read' => 'Deleted without reading',
	'pw_status_deleted_after_read' => 'Deleted after being read',
	'pw_status_readed' => 'Read',
	'pw_status_unreaded' => 'Unread',
	'pw_message' => 'Message',
	'pw_message_write' => 'New',
	'pw_messages_unreaded' => 'Unread',
	'pw_messages_sended' => 'Sent',
	'pw_messages_readed' => 'Read', 
	'pw_messages_deleted' => 'Deleted',
	'pw_send' => 'Send PM',
	'pw_reply' => 'Reply',
		
	'comments_deleted' => 'Comment has been deleted!',
	'comments_changed' => 'Comment has been modified',
	'comments_answer_info' => 'Reply to the comment.',

	'comments_below_info' => 'The comment is below the level and has been hidden.',
	'comments_add_logged' => 'Log into add a comment',
	'comments_add_comment' => 'Add a comment to the material',
	'comments_voted' => 'You cannot assess the same comment twice',
	'comments_below' => 'Comment is below the level',
	'comments_loading_info' => 'Loading comments, please wait...',
	'comments_title' => 'Comments:',
	'comments_answer' => 'Reply',
	'comments_opinion' => 'Rating:',
	'comments_votes' => 'votes:',

	'js_comments_show' => 'Show all comments',
	'comments_hidden' => 'Comments are hidden',
	'comments_add' => 'Add a comment:',
	'comments_added' => 'Comment has been added',
	'comments_flooding_time' => 'Wait %s minutes to add another comment',
	'comments_flooding_register' => 'Comments can be added after %s hours from registration. Take advantage of this time and check the content of the website.',
	'comments_add_banned' => 'Your account is temporarily banned and you cannot add new comments.',
	'ban_comme' => 'Your account is temporarily banned and you cannot rate comments.',
	'comments_add_blocked' => 'Adding new materials in comments has been blocked.',
	'comments_add_video_blocked' => 'Adding video materials in comments has been blocked.',
	'comments_vote_own' => 'You cannot vote for your own comments.',
	'comments_add_as_demot' => '<b>Do you know that you can create your own version of the material?</b><br>
						It is enough for the first word of the comment to be
						<b>"new"</b> and after double colon (::) the title may be added. The description comes afterwards. For example:<br>
						<i>new::New title::New description</i>',
	'js_comments_show_visible' => 'Comments always visible',
	'js_comments_show_hidden' => 'Comments always hidden (recommended)',
	'js_comments_hide' => 'Hide comments',
		
	'comments_empty_list' => '<h3 style="padding: 0 0 30px 30px;">No comments to be shown</h3>',
	'user_delete_account' => 'Delete your account',
		
	'archive_opinion' => 'Rating',
	'archive_votes' => 'Votes',
	'archive_author' => 'Author',
	'archive_comments' => 'Comments',
	'archive_vote_up' => 'Great',
	'right_panel_social' => 'Join us',
	'right_panel_register' => 'Join us. Create your account!',
		
	'add_cancel' => 'Cancel',
	'add_http_url' => 'Add your link to the file. Enter http:// at the beginning',
	'add_upload_source' => 'Source:',
	'add_file' => 'File:',
	'add_captcha' => 'Captcha',
	'add_file_new_input' => 'New file ?',
	'add_file_url' => 'File from link:',
	'add_file_normal' => 'File from hard drive:',
	'add_txt' => 'Your text:',
	'add_video' => 'Video:',
	'add_color' => 'Change color:',
	'add_font' => 'Choose proper font:',
	'add_tags' => 'Tags (separated with commas):',
	'add_bottom_line' => 'Description(smaller font):',
	'add_title' => 'Title:',
	'add_nazwa' => 'Material data:',
	'add_category' => 'Category:',
	'add_dodano' => 'Image has been submitted',
	'add_success_article' => 'Article has been submitted',
	'add_success_video' => 'Video has been submitted',
	'add_success_text' => 'Text has been submitted',
	'add_success_image' => 'Image has been submitted',
	'add_success_animation' => 'Animation has been submitted',
	'add_success_gallery' => 'Gallery has been successfully created',
	'add_success_ranking' => 'Ranking has been successfully created',
	'add_success_ranking_updated' => 'Ranking has been updated. New positions added.',
	'add_success' => 'Material has been submitted',
	'add_animated_files' => 'Choose files',
	'add_animated_frames' => 'Frames per sec',
	'add_animated_3' => 'Delete',
	'add_animated_merge' => 'Generator',
	'add_intro_file' => 'Intro',
		
	'add_upload_no_file' => 'No file to be uploaded.',
		
	'add_file_add' => 'Add',
	'add_file_preview' => 'Preview',
		
	'add_multiple_files' => 'Add files',
	'add_description' => 'Gallery description',
		
	'add_multiple_files' => 'Add files',
	'add_description' => 'Ranking description',
	'add_ranking_3' => 'Positions in the ranking',
	'add_ranking_limit' => 'You can add %s more positions to the ranking',
		
	'add_mem_line' => 'Upper line:',
	'add_mem_line' => 'Bottom line:',
		
	'add_edited' => 'Material has been edited',
		
	'generator_add_description' => 'By using this option, you can suggest us a new meme template. Keep in mind that:<br><br>- the image should be of good quality <br>- erotic content is not allowed<br>- acceptance of the template may take few days<br>',
	'generator_add_title' => 'Meme title:',
	'generator_add_file' => 'Image:',
	'generator_add_category' => 'Meme category:',
	'generator_add' => 'Add your meme',
	'generator_add_error_title' => 'Insert title',
	'generator_add_error_category' => 'Choose category',
	'generator_add_error_file' => 'Add a file',
	'generator_add_error_file_ext' => 'Add a proper image',
	'generator_add_success' => 'Generator added',
	'generator_add_new' => 'Suggest new generator',
	'generator_add_all' => 'All',
			
	'niepoprawny_swf' => 'SWF file is in invalid format. Choose other file.',
		
	'err_mp4_duration' => 'Video duration time exceeds the maximum time by %s seconds',
	'err_video_file_format' => 'Invalid video format',
		
	'err_gallery_folder' => 'Gallery cannot be created. Please contact the administration.',
	'err_mem_text' => 'Entered text is too long',
	'err_title' => 'Enter a title',

	'err_description' => 'Enter a description of file',

	'err_description_short' => 'Enter a longer description of the gallery without HTML tags. Max. length of the description is %s characters.',
	'err_description_short' => 'Enter a longer description of the ranking without HTML tags. Min. length of the description is %s characters.',
	'err_description_clean' => 'After removing improper HTML tags, there is no description of the gallery.',
	'err_multiple_files' => 'At least two valid files must be added to the gallery.',
	'err_multiple_files' => 'At least two valid files must be added to the ranking',
	'err_multiple_files_count' => 'Number of added files is higher than the number of positions in the ranking',
	'err_multiple_files_count_add' => 'You cannot add more positions to the ranking',
		
	'err_article' => 'Enter a title of the article',
	'err_article_x' => 'After removing improper HTML tags, there is no content of the article.',
	'err_uploaded_file' => 'Invalid image or image cannot be downloaded.',
	'err_zbytmaly' => 'Image is too small to enter additional text',
	'err_linia_1' => 'Enter a title of the article',
	'err_linia_2' => 'Enter a description of the article',
	'err_upload_source' => 'Enter a source of the material',
	'err_plik' => 'Specify localization of the file',
	'err_tagi' => 'Provide at least two tags',
	'err_file_extension' => 'File has not been added or its format is invalid. Valid formats are: jpg, jpeg, png, gif',
	'err_text_short' => 'Entered text is too short. Minimal length is %s characters.',
	'err_video_link' => 'Improper video link',
	'err_video' => 'Provide video link',
	'err_text' => 'Enter a text to be presented',
	'err_blad_pliku' => 'File error',
	'err_file_size' => 'Chosen file is too big.',
	'err_unknown' => 'Unidentified error has occurred. Contact the administration.',
	'err_up_image' => 'Adding images is currently blocked',
	'err_up_video' => 'Adding video materials is currently blocked',
	'err_up_text' => 'Adding text materials is currently blocked',
		
		
	'opis_image' => 'Images are the most popular types of materials that may be added. You can add an image and then enter two lines of text aiming at entertaining, demotivating, or disgusting our users ;)',
	'opis_text' => 'Text materials are based on adding your own text instead of an image. You can enter two lines of text',
	'opis_video' => 'Video materials can be added with a description. You can upload videos from over 130 websites',
		
		
	'podglad_publish'  => 'Publish',
	'podglad_edit'  => 'Edit',
	'podglad_delete'  => 'Delete',
	'podglad_add' => 'This is the preview of the material.',
	'podglad' => 'Do not rate, report or add the material to the favorites, as it is only a preview, not the added material.',
	'report_own_file' => 'You cannot report your own materials',
	'report_file_twice' => 'You cannot report the same material twice',
	'report_own_comments' => 'You cannot report your own comments',
	'report_own_messages' => 'You cannot report your own messages',
	'report_warning' => 'You can report the material. Nevertheless, do not overdo it, as you may be banned.',
	'report_duplicate' => 'duplicate',
	'report_content' => 'inappropriate content',
	'report_violence' => 'violence',
	'report_adult' => '18+ content',
	'report_combo' => 'combo',
	'report_spam' => 'spam, advertisement',
	'report_privacy' => 'violation of privacy',
	'report_copy' => 'copyrights infringement',
	'report_other' => 'other',
		
	'user_profile_all_files' => 'Show all in this category',
	'user_7' => 'User images panel:',
		
		
		
	'fast_no_files' => '<h1>No materials to be viewed</h1>',
		
	'user_profile_in_site' => 'Registered since:',
	'user_last' => 'Last visit:',
	'user_top' => 'Materials on the main page:',
	'user_wait' => 'Materials in the added section:',
	'user_com' => 'Comments:',
	'user_comv' => 'Points for comments:',
	'user_addv' => 'Votes for the added materials:',
	'user_logged_out' => 'You have been successfully logged out',
		
		

		
	'wiocha_2' => 'Controls:',
	'wiocha_3' => 'basic',
	'wiocha_4' => 'advanced',
	'wiocha_5' => 'Category',
	'wiocha_6' => 'Title:',
	'wiocha_7' => 'Description:',
	'wiocha_8' => 'Fill in all the blanks',
	'opiszzaladuja' => 'Choose a hilarious photo:',
	'opiszaladuj' => '
		If you want your photo to be published on the main page:<br>
		<ul>
		<li>check if a similar one has not been published yet</li>	
		<li>hide or cover faces of the individuals on the photo</li>
		<li>hide addresses, links, etc.</li>
		<li>do not copy images posted by others – it won’t work</li>
		</ul><br>Improper and invalid photos added to the website will be immediately deleted.',
		
		
		
	'common_register' => 'Register',
	'user_set_username' => 'Enter login',
	'user_register_password' => 'Enter password',
		
	'user_set_email' => 'Enter e-mail',
	'err_unknown' => 'Registration error',
	'user_wrong_email' => 'Improper e-mail address',
	'user_register_password_strength' => 'Password contains invalid characters or is too short',
	'user_password_diffrent' => 'Passwords are not the same',
	'user_register_login_used' => 'Provided login has already been taken',
	'user_register_login_error' => 'Login contains invalid characters (A-Z, 1-9) or is improper in terms of length (4 - 20 characters possible)',
	'user_register_success_verify' => 'Registration process successfully completed. An e-mail message with necessary pieces of information has been sent to your e-mail address.',
	'user_register_password_rep' => 'Repeat password',
	'common_captch_error' => 'Enter the captcha properly.',
	'user_register_email_error' => 'There is an account registered for the provided e-mail address.',
	'user_register_password_empty' => 'Fill in the password and repeat password sections',
	'user_register_rules' => 'I do accept <a target="_blank" class="highlight_text" href="/post/regulamin.html"> the Terms and Conditions </a>',
		
	'user_register_password_error' => 'Login must contain letters and digits only',

	'user_register' => 'Register',
	'user_register_success' => 'Registration procedure successfully completed. You may log in now.',
	'user_register_by_email' => 'Register via E-mail',
		
	'user_register_email_title' => 'Account activation',
		
	'user_register_email_activation' => '
		Log in data : <br /><br />Login: %s<br />Password: %s<br /><br /> To activate your account, click: <a href="%s">Account activation</a><br />',
		
	'user_register_email_active' => 'Thank you for registration on our website. In order to log in, you should use the data provided above. Remember that you need to have an account in order to comment images. If you have registered via Facebook, your account has been already created.',


		
	'captcha_instructions_visual' => 'Write the following down:',
	'captcha_instructions_audio' => 'Write what you hear:',
	'captcha_play_again' => 'Listen',
	'captcha_cant_hear_this' => 'Download in MP3 format',
	'captcha_visual_challenge' => 'Visual challenge',
	'captcha_audio_challenge' => 'Audio challenge',
	'captcha_refresh_btn' => 'Refresh the picture',
	'captcha_help_btn' => 'Help',
	'captcha_incorrect_try_again' => 'Incorrect. Try again.',
	'register_lang' => 'pl',
		
	'common_username' => 'Login',
	'common_password' => 'Password',
	'user_login_remember' => 'Remember me for 14 days',
		
	'login_1' => 'You are logged in',
	'login_2' => 'You cannot view the this content!',
	'login_3' => 'Error: No account in the database.',
	'login_konto_nieaktywne' => 'You must activate your account before logging in',
	'login_bledne_haslo' => 'Incorrect password. Click <a href="/login/reset_password">here </a> if you have forgotten your password',
	'login_brak_user' => 'There is no user with such login in our database.',
	'login_brak_pola' => 'Login or password field is empty.',
		
		
		
		
	'fast_blocked' => 'Fast browsing is currently blocked.',
	'category_not_exists' => 'No such category',
	'category_list' => 'Categories',
		
		
		
	'add_conditions' => '<ul>
				<li>uploading pornographic materials, content from Samosia, Lockerz, and other inappropriate materials leads to banning your account, as well as all other accounts created afterwards </li>
				<li>use your own or freely accessible materials only </li>
				<li>materials with links, referrals to other accounts and similar content will be deleted immediately </li></ul>',
				
	'contact_form_success' => '<h1>Message has been sent</h1>
			<p>We will try our best to reply as soon as possible</p>
			<p>You can now return to the <a href="index.html" class="read-more">main page</a>.</p>',
	'contact_form_user' => 'Name/Login:',
	'contact_form_error_user' => 'Enter your name or nick.',
	'contact_form_email' => 'E-mail:',
	'contact_form_error_email' => 'Enter proper e-mail address.',
	'contact_form_category' => 'Category:',
	'contact_form_category_question' => 'Question',
	'contact_form_category_ads' => 'Advertisement',
	'contact_form_category_problem' => 'Problem',
	'contact_form_message' => 'Message:',
	'contact_form_error_message' => 'You must enter the content of the message.',
	'contact_form_error_captcha' => 'Have you calculated it correctly?',
	'contact_form_send' => 'Send',
		
	'search_fill_field' => 'Fill in the search field',
	'search_results_found' => '%s results matching the criteria have been found.',
	'archive_vote' => 'Click, if you want the material to be moved to the added section',
		
	'meta_site_title' => 'Site name',
	'meta_site_description' => 'Description',
	'meta_site_keywords' => 'Keywords',
	
	'meta_site_footer' => 'Administration of the website shall not be held accountable for the materials published by the users. If you suppose that the material published on our website violates any law or may be inappropriate, inform the administration about this fact.',
		
	'meta_category' => 'Category: ',
	'meta_zasady' => 'Terms and Conditions concerning adding new materials',
	'meta_contact' => 'Contacting form',
	'meta_up' => 'Add a new material',
	'meta_wyloguj' => 'Log out',
	'meta_profile' => 'User’s profile: ',
	'meta_edit_profile' => 'Edit your profile',
	'meta_top' => 'Top materials',
		
	'upload_tags' => 'Tags: ',
	'comments_add_logged' => '<a onclick="userAuth('login');return false;" href="#">Log in</a>, to add comments.',
	'edycja_blad' => 'You cannot edit this material',
	'userlinks_wszystkie' => 'All',
	'userlinks_glowna' => 'Main page',
	'common_popular' => 'Popular',
	'userlinks_waiting' => 'Added',
	'userlinks_comments' => 'Comments',
	'userlinks_ulubione' => 'Favorites',
	'common_archive' => 'Archive',
	'common_private' => 'Private',
	'follow_menu' => 'Followed',
	'bottom_reklama' => 'Advertisement',
	'bottom_news' => 'News',
	'user_reset_password' => 'Remind password',
	'user_resend_activation' => 'Send the link again',
		
		
	'rss_off' => 'RSS channels are currently enabled',

	'add_only_adult' => 'Adults only?',
		
	'add_start' => 'Add:',
	'add_ban' => 'Your account has been banned and you cannot add new materials.',
	'add_account_inactive' => 'You must activate your account before adding new materials',
	'add_account_wait_register' => 'You can add new materials after %s hours from registration.',
		
	'gallery_images_count' => ' ( %s images )',
		
	'only_adult_image' => 'The content is for adults only.<br><strong> You can check it if you are 18+!</strong>',
	'only_adult_show' => 'SHOW',
	'only_adult_category' => '18 + content!',
	'only_adult_description' => 'The website contains 18+ content. If you are not interested in such materials or you are not mature, you should leave the website!',
	'only_adult_description_accept' => 'Entering the website means that you accept the Terms and Conditions, as well as confirm that you are 18+.',
		
	'item_expand_height' => 'IMAGE HIDDEN, CLICK TO SHOW IT ▼',
		
	'connect_error_accept' => 'You must accept the e-mail and login',
	'connect_header' => 'Accounts merging',
	'connect_name' => 'Suggested login',
	'connect_email' => 'E-mail address',
	'connect_accept' => 'Accept',
	'connect_loggok' => 'Data loaded',
	'connect_error' => 'Application error',
	'connect_error_blocked' => 'Access to the application has been denied',
	'connect_nlogin' => 'Login contains invalid characters (A-Z, 1-9) or is improper in terms of length (5 - 20 characters)',
	'connect_changed' => 'Login has been changed and saved',
	'connect_connected' => 'Your account has been merged with the account you have on the website.',
	'connect_description' => 'Choose a new login connected with the account or choose the recommended one. Remember that the choice may be made only once.',
		
	'premium_access' => 'Access to this part of the website is available after purchasing the Premium service only',
	'premium_access_time' => 'Your Premium account has expired: %s .<br />You must purchase another packet to take advantage of the Premium content.',
	'premium_code_ok' => 'Your Premium account will be active for %s days. Thank you.',
	'premium_code_invalid' => 'SMS code is invalid or has been used earlier.',
	'premium_service_invalid' => 'SMS service not found or has not been activated.',
	'premium_fees' => 'SMS to: {numer} with the following message : {tresc} - cost: {koszt}, service validity period: {waznosc} days <br /> {dodatkowe}',
	'premium_decription_bottom' => 'In the SMS reply, you will receive the activation code.<br />The service is available in the following telecommunication networks: Orange, Plus GSM, Era, Play, Heyah, Sami Swoi<br /><a href="http://www.dotpay.pl/index.php?content=113&amp;newlang=pl">Terms and conditions of the service</a>, <a href="http://www.dotpay.pl/reklamacje">Reclamation form</a><br />Owner of the website: <a href="mailto:{email}">{email}</a><br />SMS Service is provided by the Dotpay Company',
	'premium_sms' => 'Enter the SMS code you have received',
	'premium_sms_time' => 'Chose the validity period of your Premium Service:',
	'premium_sms_a' => 'Premium Access',
);

?>